-- 1 TASK
SELECT * FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID

-- 2 TASK
SELECT * FROM STUDENTS S
LEFT JOIN CLASSES C
ON C.CLASSID = S.CLASSID

-- 3 TASK
SELECT * FROM ORDERS O
RIGHT JOIN CUSTOMERS C
ON C.CUSTOMERID = O.CUSTOMERID

-- 4 TASK
SELECT * FROM PRODUCTS P
FULL JOIN SALES S
ON S.PRODUCTID = P.PRODUCTID

-- 5 TASK
SELECT E.NAME, E.MANAGERID FROM EMPLOYEES E
JOIN EMPLOYEES M
ON E.EMPLOYEEID = M.EMPLOYEEID

-- 6 TASK
SELECT * FROM COLORS
CROSS JOIN SIZES S

-- 7 TASK
SELECT * FROM MOVIES M
JOIN ACTORS A
ON M.MOVIEID = A.MOVIEID AND RELEASEYEAR = 2015

-- 8 TASK
SELECT O.ORDERDATE, C.CUSTOMERNAME, D.PRODUCTID FROM ORDERS O
JOIN ORDERDETAILS D
ON O.ORDERID = D.ORDERID
JOIN CUSTOMERS C
ON O.CUSTOMERID = C.CUSTOMERID

-- 9 TASK
SELECT P.PRODUCTID, SUM(S.QUANTITY) TOTALQUANTITY, P.PRODUCTID * SUM(S.QUANTITY) TOTALREVENUE  FROM PRODUCTS P
JOIN SALES S
ON P.PRODUCTID = S.PRODUCTID
GROUP BY P.PRODUCTID










