CREATE TABLE Products(
ProductID INT PRIMARY KEY,
Product_name VARCHAR(50),
Price decimal(10,2),
)
INSERT INTO products (productID, Product_name, Price) Values
(1, 'apple', 30),
(2, 'banana', 15),
(3, 'grape', 26)

ALTER TABLE Products
ADD UNIQUE (Product_name) --all products are unique
SELECT * FROM Products



INSERT INTO CATEGORIES (CATEGORYID, CATEGORYNAME) VALUES
(1, 'COMEDY'),
(2, 'HORROR')


BULK INSERT PRODUCTS
FROM 'C:\Users\Mohinur\Desktop\FILE.TXT'
WITH (
FIELDTERMINATOR =',',
ROWTERMINATOR = '\n',
FIRSTROW = 1);
DROP TABLE CATEGORIES
CREATE TABLE CATEGORIES(
CAtegoryID INT PRIMARY KEY,
CategoryName Varchar(50) UNIQUE
FOREIGN KEY (CATEGORYID) REFERENCES PRODUCTS(PRODUCTID) ON DELETE CASCADE)
SELECT * FROM PRODUCTS
SELECT * FROM CATEGORIES

ALTER TABLE PRODUCTS
ADD CHECK (PRICE>0)

ALTER TABLE PRODUCTS
ADD STOCK INT

SELECT ISNULL(NULL, 12)
------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE CUSTOMERS(
AGE INT,
CHECK (AGE >=18)
)

ALTER TABLE CUSTOMERS
ADD ID INT IDENTITY (100,10)
SELECT * FROM CUSTOMERS

CREATE TABLE EMPLOYEES2(
EMPID INT PRIMARY KEY,
EMAIL VARCHAR(50) UNIQUE
FOREIGN KEY(EMPID) REFERENCES PRODUCTS(PRODUCTID) ON DELETE  CASCADE ON UPDATE CASCADE
)
INSERT INTO EMPLOYEES2 (EMPID, EMAIL) Values
(3, 'apple'),
(5, 'banana'),
(2, 'grape')
SELECT * FROM EMPLOYEES2
