CREATE DATABASE COMPANY_DB;
USE COMPANY_DB


CREATE TABLE EMPLOYEES(
	EMPLOYEEID INT PRIMARY KEY,
	FIRSTNAME VARCHAR(50),
	LASTNAME VARCHAR(50),
	EMAIL VARCHAR(100) UNIQUE,
	PHONENUMBER VARCHAR(15) UNIQUE,
	HIREDATE DATE,
	DEPARTMENTID INT,
	POSITIONID INT,
	FOREIGN KEY(DEPARTMENTID) REFERENCES DEPARTMENTS(DEPARTMENTID) ON DELETE SET NULL,
	FOREIGN KEY (POSITIONID) REFERENCES POSITIONS(POSITIONID) ON DELETE SET NULL
)

CREATE TABLE DEPARTMENTS(
	DEPARTMENTID INT PRIMARY KEY,
	DEPARTMENTNAME VARCHAR(50),
	MANAGERID INT,
	[LOCATION] VARCHAR(50),
	BUDGET DECIMAL(10,2),
	[STATUS] VARCHAR(50),
	FOREIGN KEY (MANAGERID) REFERENCES EMPLOYEES(EMPLOYEEID) ON DELETE SET NULL
)

CREATE TABLE POSITIONS(
	POSITIONID INT PRIMARY KEY,
	POSITIONNAME VARCHAR(50),
	MINSALARY DECIMAL(10,2),
	MAXSALARY DECIMAL(10,2),
	DEPARTMENTID INT,
	REQUIREDEXPERIENCE INT,
	FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENTS(DEPARTMENTID) ON DELETE SET NULL
)

CREATE TABLE SALARIES(
	SALARYID INT PRIMARY KEY,
	EMPLOYEEID INT,
	SALARYAMOUNT DECIMAL(10,2),
	BONUS DECIMAL(10,2),
	DEDUCTIONS DECIMAL(10,2),
	PAYMENTDATE DATE,
	TAXAMOUNT DECIMAL(10,2),
	NETSALARY DECIMAL(10,2),
	FOREIGN KEY(EMPLOYEEID) REFERENCES EMPLOYEES(EMPLOYEEID) ON DELETE CASCADE
)

CREATE TABLE ATTENDANCE(
	ATTENDANCEID INT PRIMARY KEY,
	EMPLOYEEID INT,
	[DATE] DATE,
	CHECKINTIME TIME,
	CHECKOUTTIME TIME,
	TOTALHOURSWORKED DECIMAL(5,2) -- FOR EXAMPLE 8.5 HOURS,
	OVERTIMEHOURS DECIMAL(5,2) -- FOR EXAMPLE 2.5 HOURS,
	STATUS VARCHAR(50),
	FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEES(EMPLOYEEID) ON DELETE CASCADE
)

CREATE TABLE WORKSHIFTS(
	SHIFTID INT PRIMARY KEY,
	SHIFTNAME VARCHAR(50),
	STARTTIME TIME,
	ENDTIME TIME,
	SHIFTTYPE VARCHAR(50),
	STATUS VARCHAR(50)
)

CREATE TABLE EMPLOYEESHIFTS(
	ID INT PRIMARY KEY,
	EMPLOYEEID INT,
	SHIFTID INT,
	ASSIGNEDDATE DATE,
	STATUS VARCHAR(50),
	FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEES(EMPLOYEEID) ON DELETE CASCADE,
	FOREIGN KEY (SHIFTID) REFERENCES WORKSHIFTS(SHIFTID) ON DELETE CASCADE
)

CREATE TABLE PERFORMANCEREVIEWS(
	REVIEWID INT PRIMARY KEY,
	EMPLOYEEID INT,
	REVIEWDATE DATE,
	REVIEWERID INT,
	PERFORMANCESCORE INT,
	COMMENTS VARCHAR(50),
	FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEES(EMPLOYEEID) ON DELETE CASCADE,
	FOREIGN KEY (REVIEWERID) REFERENCES EMPLOYEES(EMPLOYEEID) ON DELETE NULL
) 
