CREATE DATABASE SQL5

CREATE TABLE EMPLOYEES(
EMPLOYEENAME VARCHAR (100),
SALARY INT,
AGE INT,
DEPARTMENT VARCHAR(50),
JOBTITLE VARCHAR(50),
YEAR INT,
SALES DECIMAL (10,2)
)

INSERT INTO EMPLOYEES (EMPLOYEENAME, SALARY, AGE, DEPARTMENT, JOBTITLE, YEAR, SALES) VALUES
('John Smith', 75000, 35, 'Sales', 'Sales Manager', 2023, 120000.50),
('Alice Johnson', 65000, 29, 'Marketing', 'Marketing Specialist', 2023, 95000.00),
('Robert Brown', 85000, 40, 'IT', 'Software Engineer', 2023, 0.00),
('Emily Davis', 72000, 33, 'HR', 'HR Manager', 2023, 0.00),
('Michael Wilson', 90000, 45, 'Finance', 'Financial Analyst', 2023, 0.00),
('Sarah Lee', 68000, 31, 'Sales', 'Sales Representative', 2023, 75000.75),
('David White', 78000, 38, 'Operations', 'Operations Manager', 2023, 0.00),
('Jessica Martinez', 71000, 34, 'Sales', 'Account Executive', 2023, 85000.25),
('William Anderson', 88000, 42, 'IT', 'IT Manager', 2023, 0.00),
('Laura Thomas', 74000, 36, 'Marketing', 'Brand Manager', 2023, 91000.00);


CREATE TABLE SALES(
PRODUCTNAME VARCHAR (50),
PRICE DECIMAL(10,2),
REGION VARCHAR (50),
SALES DECIMAL(10, 2),
CATEGORY VARCHAR(50),
CUSTOMER VARCHAR(50),
[ORDER VALUE] INT,
[ORDER QUANTITY] INT,
SALESAMOUNT INT,
ORDERS INT
)

INSERT INTO SALES (PRODUCTNAME, PRICE, REGION, SALES, CATEGORY, CUSTOMER, [ORDER VALUE], [ORDER QUANTITY], SALESAMOUNT, ORDERS) VALUES
('Laptop', 1200.00, 'North America', 15000.50, 'Electronics', 'ABC Corp', 15000, 10, 15000, 5),
('Smartphone', 800.00, 'Europe', 12000.00, 'Electronics', 'XYZ Ltd', 12000, 15, 12000, 6),
('Headphones', 150.00, 'Asia', 4500.75, 'Accessories', 'Tech Solutions', 4500, 30, 4500, 10),
('Office Chair', 250.00, 'South America', 6500.25, 'Furniture', 'Global Enterprises', 6500, 25, 6500, 8),
('Tablet', 500.00, 'North America', 10000.50, 'Electronics', 'ABC Corp', 10000, 20, 10000, 7),
('Printer', 300.00, 'Europe', 7500.75, 'Office Supplies', 'XYZ Ltd', 7500, 15, 7500, 6),
('Monitor', 400.00, 'Asia', 9000.25, 'Electronics', 'Tech Solutions', 9000, 18, 9000, 7),
('Desk', 600.00, 'South America', 12000.00, 'Furniture', 'Global Enterprises', 12000, 20, 12000, 5),
('External Hard Drive', 200.00, 'North America', 5000.50, 'Accessories', 'ABC Corp', 5000, 25, 5000, 9),
('Smartwatch', 350.00, 'Europe', 8000.75, 'Wearables', 'XYZ Ltd', 8000, 22, 8000, 8);


SELECT MIN(PRICE) FROM SALES -- 1 QUESTION

SELECT MAX(SALARY) FROM EMPLOYEES -- 2 QUESTION

SELECT COUNT(*) FROM SALES --3 QUESTION, THERE IS NO NEED FOR ANOTHER TABLE, ALL INFORMATION ABOUT CUSTOMERS COULD BE FOUND IN SALES TABLE SINCE OUR DATABASE IS NOT BIG

SELECT COUNT(DISTINCT CATEGORY) FROM SALES --4 QUESTION

SELECT PRODUCTNAME, SUM(SALES) FROM SALES
GROUP BY PRODUCTNAME --5 QUESTION

SELECT EMPLOYEENAME, AVG(AGE) FROM EMPLOYEES
GROUP BY EMPLOYEENAME -- 6 QUESTION, NAME OF EMPLOYEES ABD THEIR AGE

SELECT DEPARTMENT, COUNT(*) AS EMPLOYEECNT FROM EMPLOYEES
GROUP BY DEPARTMENT -- 7 QUESTION

SELECT CATEGORY,
MIN(PRICE) AS MINPRICE,
MAX(PRICE) AS MAXPRICE
FROM SALES
GROUP BY CATEGORY -- 8 QUESTION

SELECT REGION, SUM(SALES) FROM SALES
GROUP BY REGION -- 9 QUESTION

SELECT DEPARTMENT, COUNT(*) FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING COUNT(*) > 5 -- 10 QUESTION

-----------------------------------------------------------------------------------------------------------
SELECT CATEGORY,
SUM(SALES) AS TOTALSALES,
AVG(SALES) AS AVERAGESALES
FROM SALES
GROUP BY CATEGORY --11 QUESTION

SELECT COUNT(DISTINCT JOBTITLE) FROM EMPLOYEES --12 QUESTION

SELECT DEPARTMENT, MIN(SALARY), MAX(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT -- 13 QUESTION

SELECT DEPARTMENT, AVG(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT --14 QUESTION

SELECT DEPARTMENT, AVG(SALARY), COUNT(*) FROM EMPLOYEES
GROUP BY DEPARTMENT -- 15 QUESTION

SELECT PRODUCTNAME, AVG(PRICE) FROM SALES
GROUP BY PRODUCTNAME
HAVING AVG(PRICE) > 100 -- 16 QUESTION

SELECT SUM(SALES), COUNT(DISTINCT PRODUCTNAME) FROM SALES
GROUP BY PRODUCTNAME
HAVING SUM(SALES) > 100 -- 17 QUESTION

SELECT YEAR, SUM(SALES) FROM EMPLOYEES
GROUP BY YEAR -- 18 QUESTION

SELECT REGION, COUNT(*) FROM SALES
GROUP BY REGION -- 19 QUESTION

SELECT DEPARTMENT, SUM(SALES) FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING SUM(SALES) > 100000 -- 20 QUESTION

----------------------------------------------------------------------------------------------------------

SELECT CATEGORY, AVG(SALES) FROM SALES
GROUP BY CATEGORY
HAVING AVG(SALES) > 200 -- 21 QUESTION

SELECT EMPLOYEENAME, SUM(SALES) FROM EMPLOYEES
GROUP BY EMPLOYEENAME
HAVING SUM(SALES) > 5000 -- 22 QUESTION

SELECT DEPARTMENT, SUM(SALARY), AVG(SALARY) FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING AVG(SALARY) > 6000 --23 QUESTION

SELECT CUSTOMER, MIN([ORDER VALUE]), MAX([ORDER VALUE]) FROM SALES
GROUP BY CUSTOMER
HAVING MIN([ORDER VALUE]) > 50 -- 24 QUESTION

SELECT REGION, SUM(SALES),COUNT(DISTINCT PRODUCTNAME) FROM SALES
GROUP BY REGION
HAVING COUNT(PRODUCTNAME) > 10 -- 25 QUESTION

SELECT CATEGORY, MIN([ORDER QUANTITY]), MAX([ORDER QUANTITY]) FROM SALES
GROUP BY CATEGORY -- 26 QUESTION

-- WE WERE TOLD NOT TO DO PIVOT EXERCISES, AND THERE ARE 27, 28, 29, AND 30 QUESTIONS. BASE YOUR SCORE ON THE DONE ON TOP 26 QUESTIONS.





